In [13]:
import pandas as pd

#파일 불러오기
blk = pd.read_csv('C:/가을/대외활동/공모전/성남시 데이터 분석 아이디어 제안 공모전/data/fake_blk_card.csv', encoding='utf-8') 
blk

,STD_YM,GSD_NM,SGG_NM,EMD_NM,BLK_CD,CARD_POS,CLN_GENDER,CLN_AGE,CLN_REG_YN,RY_L_CD,CARD_AMT,CARD_CNT
0,202301,경기도,성남시,정자동,BLK001,개인,남,10대,거주,외식,79806,16
1,202301,경기도,성남시,정자동,BLK001,개인,남,20대,거주,외식,59646,17
2,202301,경기도,성남시,정자동,BLK001,개인,남,30대,거주,외식,79322,23
3,202301,경기도,성남시,정자동,BLK001,개인,남,40대,거주,외식,19190,30
4,202301,경기도,성남시,정자동,BLK001,개인,남,50대,거주,외식,49661,18
...,...,...,...,...,...,...,...,...,...,...,...,...
347,202309,경기도,성남시,정자동,BLK002,개인,남,60대이상,거주,의료,86106,30
348,202309,경기도,성남시,정자동,BLK002,개인,여,10대,거주,의료,54414,38
349,202309,경기도,성남시,정자동,BLK002,개인,여,20대,거주,의료,23386,42
350,202309,경기도,성남시,정자동,BLK002,개인,여,30대,거주,의료,64460,18
351,202309,경기도,성남시,정자동,BLK002,개인,여,40대,거주,의료,33474,30

In [15]:
blk = blk[['EMD_NM','BLK_CD','CLN_GENDER','CLN_AGE','RY_L_CD', 'CARD_AMT','CARD_CNT']]
blk_60 = blk[blk['CLN_AGE']=='60대이상']
blk_60_medical = blk_60[blk_60['RY_L_CD'] == '의료']
blk_60_medical

    EMD_NM  BLK_CD CLN_GENDER CLN_AGE RY_L_CD  CARD_AMT  CARD_CNT
317    정자동  BLK002          여   60대이상      의료     10798        24
323    정자동  BLK003          남   60대이상      의료     87506        39
329    정자동  BLK003          여   60대이상      의료     10893        20
335    정자동  BLK001          남   60대이상      의료     41186        29
341    정자동  BLK001          여   60대이상      의료     20785        40
347    정자동  BLK002          남   60대이상      의료     86106        30

In [16]:
blk_60_medical.to_csv('blk60medical.csv', index=False, encoding='utf-8-sig')