In [1]:
import pandas as pd

In [2]:
#파일 불러오기
population = pd.read_csv('C:/가을/대외활동/공모전/성남시 데이터 분석 아이디어 제안 공모전/data/fake_population.csv', encoding='utf-8') 
population

,STD_YM,STD_YMD,HCODE,M_0009,M_1014,M_1519,M_2024,M_2529,M_3034,M_3539,...,W_3539,W_4044,W_4549,W_5054,W_5559,W_6064,W_6569,W_7000,X_COORD,Y_COORD
0,202301,2023-01-01,411310000,38,28,14,42,7,20,38,...,29,37,1,20,32,11,21,43,960230.6,1945247.7
1,202301,2023-01-01,411310001,41,27,15,14,46,50,43,...,25,1,19,27,46,6,43,7,960343.9,1949093.2
2,202301,2023-01-01,411310002,35,49,39,3,1,5,41,...,13,22,39,20,15,44,17,46,968287.4,1943567.5
3,202301,2023-01-01,411310003,44,40,28,14,44,0,24,...,32,4,41,38,40,27,6,8,966233.0,1943309.0
4,202301,2023-01-01,411310004,47,22,23,36,34,43,39,...,38,26,8,14,14,25,41,12,962017.2,1948957.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115,202412,2024-12-01,411310000,20,50,37,19,28,50,3,...,26,40,0,7,22,37,5,21,962543.9,1943618.5
116,202412,2024-12-01,411310001,11,5,25,26,7,18,41,...,37,48,45,48,7,42,19,32,963388.6,1948025.9
117,202412,2024-12-01,411310002,48,41,42,40,8,23,36,...,10,12,45,44,0,39,43,18,964110.2,1949076.1
118,202412,2024-12-01,411310003,44,11,47,32,44,25,38,...,19,17,17,1,3,29,32,35,963690.5,1941210.3
119,202412,2024-12-01,411310004,27,39,19,48,32,11,50,...,17,50,8,38,27,2,19,5,961205.6,1949024.5

In [3]:
#60세 이상 인구 추출
pop60up = population[['HCODE','X_COORD','Y_COORD','M_6064','M_6569', 'M_7000','W_6064', 'W_6569', 'W_7000',]]
pop60up['Mtotal'] = population[['M_6064','M_6569', 'M_7000']].sum(axis=1)
pop60up['Wtotal'] = population[['W_6064','W_6569', 'W_7000']].sum(axis=1)
pop60up['Total'] = population[['M_6064','M_6569', 'M_7000','W_6064','W_6569', 'W_7000']].sum(axis=1)
pop60up

C:\Users\lotte\AppData\Local\Temp\ipykernel_28924\3517904991.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  pop60up['Mtotal'] = population[['M_6064','M_6569', 'M_7000']].sum(axis=1)
C:\Users\lotte\AppData\Local\Temp\ipykernel_28924\3517904991.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  pop60up['Wtotal'] = population[['W_6064','W_6569', 'W_7000']].sum(axis=1)
C:\Users\lotte\AppData\Local\Temp\ipykernel_28924\3517904991.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  pop60up['Total'] = population[['M_6064','M_6569', 'M_7000','W_6064','W_6569', 'W_7000']].sum(axis=1)

,HCODE,X_COORD,Y_COORD,M_6064,M_6569,M_7000,W_6064,W_6569,W_7000,Mtotal,Wtotal,Total
0,411310000,960230.6,1945247.7,23,35,39,11,21,43,97,75,172
1,411310001,960343.9,1949093.2,20,8,38,6,43,7,66,56,122
2,411310002,968287.4,1943567.5,43,33,9,44,17,46,85,107,192
3,411310003,966233.0,1943309.0,43,7,23,27,6,8,73,41,114
4,411310004,962017.2,1948957.6,34,36,46,25,41,12,116,78,194
...,...,...,...,...,...,...,...,...,...,...,...,...
115,411310000,962543.9,1943618.5,21,11,44,37,5,21,76,63,139
116,411310001,963388.6,1948025.9,34,39,13,42,19,32,86,93,179
117,411310002,964110.2,1949076.1,20,50,38,39,43,18,108,100,208
118,411310003,963690.5,1941210.3,26,45,22,29,32,35,93,96,189
119,411310004,961205.6,1949024.5,28,40,9,2,19,5,77,26,103

In [4]:
from pyproj import Transformer

# EPSG:5179 → EPSG:4326 (위도/경도) 변환기 정의
transformer = Transformer.from_crs("EPSG:5179", "EPSG:4326", always_xy=True)

# 변환 적용
lon, lat = transformer.transform(pop60up['X_COORD'].values, pop60up['Y_COORD'].values)

# DataFrame에 위도/경도 열 추가
pop60up['lon'] = lon
pop60up['lat'] = lat

C:\Users\lotte\AppData\Local\Temp\ipykernel_28924\3676289893.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  pop60up['lon'] = lon
C:\Users\lotte\AppData\Local\Temp\ipykernel_28924\3676289893.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  pop60up['lat'] = lat

In [10]:
# 좌표도 평균으로 포함하고 싶을 경우
grouped= pop60up.groupby('HCODE', as_index=False).agg({
    'Mtotal': 'sum',
    'Wtotal': 'sum',
    'Total': 'sum',
    'X_COORD': 'mean',
    'Y_COORD': 'mean',
    'lon': 'mean',
    'lat': 'mean'
})

print(grouped)

       HCODE  Mtotal  Wtotal  Total        X_COORD       Y_COORD         lon  \
0  411310000    1896    1844   3740  965535.758333  1.944859e+06  127.110077
1  411310001    1779    1989   3768  965468.525000  1.945677e+06  127.109281
2  411310002    1691    1918   3609  964383.933333  1.944934e+06  127.097043
3  411310003    1764    1991   3755  965586.695833  1.944364e+06  127.110674
4  411310004    1953    1795   3748  965101.054167  1.944405e+06  127.105180

         lat
0  37.502350
1  37.509721
2  37.502984
3  37.497892
4  37.498245

In [11]:
grouped.to_csv('pop60up_grouped2.csv', index=False, encoding='utf-8-sig')